spring:
  application: name=ms-email-v1
  # MAILTRAP
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: be90af9f767cf6
    password: bafc948089a797
    properties:
      email:
        smtp:
          auth: true
          starttls:
            enable: true

  # KAFKA
  kafka:
    bootstrap-servers: localhost:9092

kafka:
  topic:
    partitions: 1
    replication-factor: 1

server:
  port: 8082
  servlet:
    context-path: /api/v1
